//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUHOI()
        {
            this.BODETHI_CAUHOI = new HashSet<BODETHI_CAUHOI>();
        }
    
        public string MACAUHOI { get; set; }
        public string TENCAUHOI { get; set; }
        public string DAPAN_A { get; set; }
        public string DAPAN_B { get; set; }
        public string DAPAN_C { get; set; }
        public string DAPAN_D { get; set; }
        public string DAPANDUNG { get; set; }
        public string MAHOCPHAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BODETHI_CAUHOI> BODETHI_CAUHOI { get; set; }
        public virtual HOCPHAN HOCPHAN { get; set; }
    }
}
