//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTHI
    {
        public string MAHOCPHAN { get; set; }
        public string MALOPHOCPHAN { get; set; }
        public System.DateTime NGAYTHI { get; set; }
        public string THOIGIANTHI { get; set; }
        public string THOILUONGTHI { get; set; }
        public string GHICHU { get; set; }
        public string PHONGTHI { get; set; }
        public string GV01 { get; set; }
        public string GV02 { get; set; }
        public int ID { get; set; }
    
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual LOPHOCPHAN LOPHOCPHAN { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual GIANGVIEN GIANGVIEN1 { get; set; }
    }
}
