//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string LOAITK { get; set; }
        public string TENTK { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string MSSV { get; set; }
        public string MAGV { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
